spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres



  sql:
    init:
      mode: always
      schema-locations: classpath*:db/schema.sql
#      data-locations: classpath*:db/data.sql


